### ISSUE TITLE
Diet templates

### ISSUE THREAD

**Issue by chances** [staysail/nova-dvelop#11]
Please add support for Vibe's templating language.

See [Diet template documentation](https://vibed.org/templates/diet).

**Comment by chances** [comment]
I'm considering implementing an XML syntax on my own. If I do, I'll contribute it back here in a new PR.

**Comment by gdamore** [comment]
Please do feel free to submit PRs.  I'm not actually using Nova anymore in my day-to-day (it got too crashy for me), but I'm happy to integrate updates.

I've just done a bunch of updates so that should help, but you'll almost certainly be wishing for the missing string interpolation support.  (It's only todo list.)

**Comment by gdamore** [comment]
So, I'm unlikely to implement support for "Diet" here.  Someone else could create such a plugin, but its definitely out of scope for *this* project.
